### ISSUE TITLE
Unable to create mamba environment

### ISSUE THREAD

**Issue by Virschnieder** [maxfrei750/paddle#3]
Actually i have installed mamba in a linux system and I tried running the command 
`mamba env create --file environment.yaml`
The packages were installed suceesfully (There  were around 338 packages with a total storage of 2 GB) but I encountered the following error in the pip dependency resolution.
![image](https://user-images.githubusercontent.com/77125368/180455164-cd3775a7-1bfa-4ba0-a711-cfa2609d4844.png)

**Comment by maxfrei750** [comment]
While it's not nice, it also says

>Requirement already satisfied: opencv==4.5.*

And

>Found existing installation. 

So I guess you should be fine for now. Please test, if the demos work, and let me know the result.

**Comment by Virschnieder** [comment]
Although the packages were installed succesfully,, when I ran the command `conda activate paddle` it wasn't able to detect the enviornment inside /envs/ , also while pip resoution the overall output was __failed__ so the environment wasn't created successfully.

**Comment by maxfrei750** [comment]
I see. Then please try to remove `- opencv-python==4.5.*` (Line 29) from https://github.com/maxfrei750/paddle/blob/a9d32d9943766b653c1cb82250583ebacfd082c8/environment.yaml

rebuild and test again.

**Comment by maxfrei750** [comment]
I removed the line and tested and everything works, since opencv is implicitly required by another dependency. You should no longer see the error.
