### ISSUE TITLE
No module found paddle

### ISSUE THREAD

**Issue by Rajarshi1001** [maxfrei750/paddle#4]
I have successfully created the conda environment and on runing the jupyter lab, I went inside the __demos/03_analyze_dataset/analyze_dataset__ notebook. On running the first cell itself I encountered with the following error.
![image](https://user-images.githubusercontent.com/79023293/180466370-bf504713-44cf-41c4-8b66-eede18f6dc89.png)

**Comment by Rajarshi1001** [comment]
Could you please tell how to test the model on my sample image as I am unable to figure it out, I try running the juyter notebooks but each of the notebooks throws an error.

**Comment by maxfrei750** [comment]
It seems that `paddle` was not added to your python `PYTHONPATH`. Some IDEs (like PyCharm, which I used for the development and testing) do this automatically. If yours does not, then you need to add it in the code (using something like [this](https://stackoverflow.com/a/16114586/11652760)).

**Comment by maxfrei750** [comment]
I wrote a small `setup.py`, which allows `paddle` to be installed in your conda environment (see updated instructions in readme).
